#!/usr/bin/env python3
"""Build colored ASCII CCTV feed data from source MOVs for ./signal."""

import base64
import json
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "js" / "signal-feed-data.js"

SOURCES = [
    {"path": Path("/Users/raynaldorusi/Downloads/IMG_2634.MOV"), "start": 1.0, "duration": 4.0},
    {"path": Path("/Users/raynaldorusi/Downloads/IMG_2635.MOV"), "start": 0.8, "duration": 4.0},
]

WIDTH = 80
HEIGHT = 24
FPS = 8
CHARS = " .'`^\",:;Il!i><~+_-?][}{1)(|\\/tfjrxnuvczXYUJCLQ0OZmwqpdbkhao*#MW&8%B@$"


def extract_frames(source):
    path = source["path"]
    if not path.exists():
        raise SystemExit(f"missing source video: {path}")

    vf = f"fps={FPS},scale={WIDTH}:{HEIGHT}:flags=lanczos"
    cmd = [
        "ffmpeg",
        "-hide_banner",
        "-loglevel",
        "error",
        "-ss",
        str(source["start"]),
        "-i",
        str(path),
        "-t",
        str(source["duration"]),
        "-vf",
        vf,
        "-f",
        "rawvideo",
        "-pix_fmt",
        "rgb24",
        "pipe:1",
    ]
    proc = subprocess.run(cmd, check=True, stdout=subprocess.PIPE)
    raw = proc.stdout
    frame_size = WIDTH * HEIGHT * 3
    if len(raw) % frame_size != 0:
        raw = raw[: len(raw) - (len(raw) % frame_size)]
    frames = []
    for i in range(0, len(raw), frame_size):
        chunk = raw[i : i + frame_size]
        cells = []
        for y in range(HEIGHT):
            row_start = y * WIDTH * 3
            for x in range(WIDTH):
                j = row_start + x * 3
                r, g, b = chunk[j], chunk[j + 1], chunk[j + 2]
                lum = 0.299 * r + 0.587 * g + 0.114 * b
                ci = int(lum / 255 * (len(CHARS) - 1))
                cells.append(CHARS[ci])
                cells.append(f"{r:02x}{g:02x}{b:02x}")
        frames.append(base64.b64encode("".join(cells).encode("ascii")).decode("ascii"))
    return frames


def main():
    all_frames = []
    for source in SOURCES:
        all_frames.extend(extract_frames(source))

    payload = {
        "w": WIDTH,
        "h": HEIGHT,
        "fps": FPS,
        "frames": all_frames,
    }

    OUT.write_text(
        "/* generated by scripts/build-signal-feed.py — do not edit */\n"
        "(function (g) {\n"
        "  g.SIGNAL_FEED = "
        + json.dumps(payload, separators=(",", ":"))
        + ";\n"
        "})(window);\n",
        encoding="utf-8",
    )
    print(f"wrote {OUT} ({len(all_frames)} frames, {OUT.stat().st_size // 1024} KB)")


if __name__ == "__main__":
    main()
