#!/usr/bin/env python3
"""Build colored pixel-grid CCTV feeds from source MOVs for ./signal."""

import base64
import json
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "js" / "signal-feed-data.js"

# ASCILINE-style density: wide grid, pixel blocks (rgb per cell, no glyph ramp).
WIDTH = 168
HEIGHT = 47
FPS = 10

CAMS = [
    {
        "id": "IPcam_1",
        "path": Path("/Users/raynaldorusi/Downloads/IMG_2634.MOV"),
        "start": 1.0,
        "duration": 4.0,
    },
    {
        "id": "IPcam_2",
        "path": Path("/Users/raynaldorusi/Downloads/IMG_2635.MOV"),
        "start": 0.8,
        "duration": 4.0,
    },
]


def extract_frames(source):
    path = source["path"]
    if not path.exists():
        raise SystemExit(f"missing source video: {path}")

    vf = f"fps={FPS},scale={WIDTH}:{HEIGHT}:flags=lanczos"
    cmd = [
        "ffmpeg",
        "-hide_banner",
        "-loglevel",
        "error",
        "-ss",
        str(source["start"]),
        "-i",
        str(path),
        "-t",
        str(source["duration"]),
        "-vf",
        vf,
        "-f",
        "rawvideo",
        "-pix_fmt",
        "rgb24",
        "pipe:1",
    ]
    proc = subprocess.run(cmd, check=True, stdout=subprocess.PIPE)
    raw = proc.stdout
    frame_size = WIDTH * HEIGHT * 3
    if len(raw) % frame_size != 0:
        raw = raw[: len(raw) - (len(raw) % frame_size)]
    frames = []
    for i in range(0, len(raw), frame_size):
        chunk = raw[i : i + frame_size]
        frames.append(base64.b64encode(chunk).decode("ascii"))
    return frames


def main():
    cams = []
    for cam in CAMS:
        frames = extract_frames(cam)
        cams.append({"id": cam["id"], "frames": frames})
        print(f"  {cam['id']}: {len(frames)} frames from {cam['path'].name}")

    payload = {
        "w": WIDTH,
        "h": HEIGHT,
        "fps": FPS,
        "mode": "pixel",
        "cams": cams,
    }

    OUT.write_text(
        "/* generated by scripts/build-signal-feed.py — do not edit */\n"
        "(function (g) {\n"
        "  g.SIGNAL_FEED = "
        + json.dumps(payload, separators=(",", ":"))
        + ";\n"
        "})(window);\n",
        encoding="utf-8",
    )
    print(f"wrote {OUT} ({OUT.stat().st_size // 1024} KB)")


if __name__ == "__main__":
    main()
